#!/usr/bin/env python3
"""Regenerate ChatGPT knowledge-files from canonical source.

Canonical source (single source of truth — claude-skills repo):
  ai-build-partner/kit-files/    (00-04 MSP + brand + voice + personas + user-context)
  ai-build-partner/modules/      (21 module specs for 05-modules bundle)

Targets (overwritten — git is the safety net, in ship-it-system repo):
  chatgpt-apps/free-ai-build-partner/knowledge-files/
      00-master-system-prompt.md
      01-brand-guide.md
      02-voice-dna.md
      03-audience-personas.md
      04-user-context-template.md
      05-modules.md   (concatenated from modules/ in retrieval-priority order)

  chatgpt-apps/paid-ship-it-system/knowledge-files/
      00-04 (same as free)

Replaces the older ai-build-partner-kit/regen-05-modules.sh (folded in here).

Run locally:
    python3 ~/github/claude-skills/scripts/sync-gpt-knowledge-files.py
    cd ~/github/ship-it-system && git diff chatgpt-apps/

In CI: claude-skills workflow checks out ship-it-system alongside; sets
SHIP_IT_SYSTEM_PATH env var to the checkout location.
"""
from __future__ import annotations

import hashlib
import os
import shutil
import sys
from pathlib import Path

CLAUDE_SKILLS = Path(__file__).resolve().parents[1]
CANONICAL_KIT = CLAUDE_SKILLS / "ai-build-partner/kit-files"
CANONICAL_MODULES = CLAUDE_SKILLS / "ai-build-partner/modules"

SHIP_IT_SYSTEM = Path(os.environ.get(
    "SHIP_IT_SYSTEM_PATH",
    str(Path.home() / "github/ship-it-system"),
))

KIT_FILES = (
    "00-master-system-prompt.md",
    "01-brand-guide.md",
    "02-voice-dna.md",
    "03-audience-personas.md",
    "04-user-context-template.md",
)

# Both GPTs get the same 00-04 kit-files. The free GPT additionally gets the
# 05-modules.md consolidation. The paid GPT has its own 05-12 files (kit playbook,
# MOS, etc.) generated by separate tooling — not touched here.
GPT_TARGETS = (
    SHIP_IT_SYSTEM / "chatgpt-apps/free-ai-build-partner/knowledge-files",
    SHIP_IT_SYSTEM / "chatgpt-apps/paid-ship-it-system/knowledge-files",
)
FREE_GPT_DIR = SHIP_IT_SYSTEM / "chatgpt-apps/free-ai-build-partner/knowledge-files"

# Retrieval order for the 05-modules.md bundle — most-used modules first so
# file-search weights them higher in chunk-relevance.
MODULES_ORDER = (
    "scope.md", "sprint.md", "discovery.md", "validate.md", "diagnose.md",
    "audit.md", "launch.md", "roadmap.md", "stuck.md", "context.md",
    "ship-announcement.md", "launch-emails.md", "landing-page.md", "funnel.md",
    "audience-from-zero.md", "day-job-decision.md", "conversation-finder.md",
    "dm-personalizer.md", "outreach-batch.md", "idea-bank.md", "full-pipeline.md",
)

MODULES_HEADER = """# AI Build Partner — Modules

All free-tier module specs in one knowledge file. Each module has its own `<process>` block with verbatim opening, step-by-step flow, and artifact shape. The model uses these to route `/unstuck <command>` invocations and to produce the canonical output for each module.

**Bundled here for ChatGPT knowledge-file upload.** On Claude.ai, the same content loads as separate `modules/*.md` files in the skill bundle. Single source of truth: `claude-skills/ai-build-partner/modules/`. Regenerate with `python3 scripts/sync-gpt-knowledge-files.py`.

---
"""


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:8]


def sync_kit_files(canonical: Path, target_dir: Path) -> list[tuple[str, str]]:
    """Copy 00-04 from canonical → target. Returns [(filename, status)]."""
    results = []
    target_dir.mkdir(parents=True, exist_ok=True)
    for name in KIT_FILES:
        src = canonical / name
        if not src.exists():
            raise SystemExit(f"ERROR: canonical kit-file missing: {src}")
        dst = target_dir / name
        if dst.exists() and sha(dst) == sha(src):
            results.append((name, "unchanged"))
            continue
        shutil.copyfile(src, dst)
        results.append((name, "updated"))
    return results


def regen_modules_bundle(canonical_modules: Path, output: Path) -> tuple[int, int]:
    """Concat modules/ → 05-modules.md in retrieval-priority order.

    Returns (modules_written, total_bytes).
    """
    if not canonical_modules.is_dir():
        raise SystemExit(f"ERROR: canonical modules dir missing: {canonical_modules}")

    parts = [MODULES_HEADER]
    written = 0
    for fname in MODULES_ORDER:
        src = canonical_modules / fname
        if not src.exists():
            print(f"  WARN: module not found in canonical: {fname}", file=sys.stderr)
            continue
        slug = fname[:-3]  # strip .md
        parts.append(f"\n## Module: /unstuck {slug}\n")
        parts.append(f"<!-- source: claude-skills/ai-build-partner/modules/{fname} -->\n")
        parts.append(src.read_text())
        parts.append("\n---\n")
        written += 1

    output.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(parts)
    output.write_text(body)
    return written, len(body.encode())


def main() -> int:
    print(f"Canonical kit-files: {CANONICAL_KIT}")
    print(f"Canonical modules:   {CANONICAL_MODULES}")
    print(f"ship-it-system:      {SHIP_IT_SYSTEM}")
    print()

    if not CANONICAL_KIT.is_dir():
        print(f"ERROR: canonical kit-files dir not found: {CANONICAL_KIT}", file=sys.stderr)
        return 1
    if not SHIP_IT_SYSTEM.is_dir():
        print(f"ERROR: ship-it-system not found at {SHIP_IT_SYSTEM} (set SHIP_IT_SYSTEM_PATH)", file=sys.stderr)
        return 1

    total_updated = 0
    total_unchanged = 0

    for target in GPT_TARGETS:
        rel = target.relative_to(SHIP_IT_SYSTEM)
        print(f"→ ship-it-system/{rel}")
        results = sync_kit_files(CANONICAL_KIT, target)
        for name, status in results:
            print(f"    {status:9s}  {name}")
            if status == "updated":
                total_updated += 1
            else:
                total_unchanged += 1
        print()

    # Free GPT additionally gets the modules bundle.
    rel_modules = (FREE_GPT_DIR / "05-modules.md").relative_to(SHIP_IT_SYSTEM)
    print(f"→ ship-it-system/{rel_modules}  (regen)")
    count, size_bytes = regen_modules_bundle(CANONICAL_MODULES, FREE_GPT_DIR / "05-modules.md")
    print(f"    modules: {count}/{len(MODULES_ORDER)}, size: {size_bytes // 1024} KB")
    print()

    print(f"Summary: {total_updated} updated, {total_unchanged} unchanged across {len(GPT_TARGETS)} GPT dirs.")
    print("Review with: cd ~/github/ship-it-system && git diff chatgpt-apps/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
